### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by ansarizafar** [codexguy/CodexMicroORM#2]
What is the status of this project? Is it in active development or dead?

**Comment by codexguy** [comment]
It's active, but relatively stable at the moment, which is why there have not been many commits. The recent commit was fairly significant, including nullable reference type changes.

**Comment by codexguy** [comment]
It's active, but relatively stable at the moment, which is why there have not been many commits. The recent commit was fairly significant, including nullable reference type changes.
